#!/bin/bash

export SHELL_RUN=/opt/home/amir/work/cmaq/modified/4.5.1/base/1208/fwd/shells

export SDATE=20070727
export IDATE=20070726
export SJDATE=2007208

for ((i=0;i<=0;i++)); do

export APPL=`datshift $SDATE $i`	
export APPL0=`datshift $IDATE $i`	
export JDATE=`expr $SJDATE + $i`
export APPL=`echo "$APPL" | tail -5 | head -1 | cut -d " " -f1`
export APPL0=`echo "$APPL0" | tail -5 | head -1 | cut -d " " -f1`
export JDATE=`echo "$JDATE" | tail -5 | head -1 | cut -d " " -f1`

echo $APPL $APPL0 $JDATE

sed "s:TODAY:$APPL:g" $SHELL_RUN/run.template | sed "s:YESTERDAY:$APPL0:g" | sed "s:JDATE:$JDATE:g" > run.day

chmod 755 ./run.day
./run.day
rm ./run.day

done
