#!/bin/bash

export SHELL_RUN=/opt/home/apappin/cmaqupdate/bwd/shells

export SDATE=20070930
export IDATE=20071001
export SJDATE=2007273
export EJDATE=2007274

for ((i=0;i<=159;i++)); do

export APPL=`datshift $SDATE -$i`	
export APPL0=`datshift $IDATE -$i`	
export JDATE=`expr $SJDATE - $i`
export EDATE=`expr $EJDATE - $i`
export APPL=`echo "$APPL" | tail -5 | head -1 | cut -d " " -f1`
export APPL0=`echo "$APPL0" | tail -5 | head -1 | cut -d " " -f1`
export JDATE=`echo "$JDATE" | tail -5 | head -1 | cut -d " " -f1`
export EDATE=`echo "$EDATE" | tail -5 | head -1 | cut -d " " -f1`

echo $APPL $APPL0 $JDATE $EDATE

sed "s:TODAY:$APPL:g" $SHELL_RUN/run.template | sed "s:TOMORROW:$APPL0:g" | sed "s:JDATE:$JDATE:g" | sed "s:EDATE:$EDATE:g" > run.day

chmod 755 ./run.day
./run.day
rm run.day

done
