! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : CMAQ_CB4_Parameters.f90
! Time                 : Tue Apr 18 15:57:11 2006
! Working directory    : /home/amir/Desktop/KPP/kpp-2.1
! Equation file        : CMAQ_CB4.kpp
! Output root filename : CMAQ_CB4
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE KPP_Pars

  USE KPP_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: KPPNSP = 72 ! changed from 77, disregarding fixed 
! NVAR - Number of Variable species
! INTEGER, PARAMETER :: NVAR = 72 
! NVARACT - Number of Active species
!  INTEGER, PARAMETER :: NVARACT = 69 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 5 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: KPPNRCT = 214 
! NVARST - Starting of variables in conc. vect.
!  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
!  INTEGER, PARAMETER :: NFIXST = 73 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 845 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 946 
! CNVAR - (NVAR+1) Number of elements in compressed row format
!  INTEGER, PARAMETER :: CNVAR = 73 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 860 
! NLOOKAT - Number of species to look at
!  INTEGER, PARAMETER :: NLOOKAT = 77 
! NMONITOR - Number of species to monitor
!  INTEGER, PARAMETER :: NMONITOR = 4 
! NMASS - Number of atoms to check mass balance
!  INTEGER, PARAMETER :: NMASS = 1 
! PI - Value of pi
!  REAL(kind=dp), PARAMETER :: PI = 3.14159265358979 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_SULF = 1 
  INTEGER, PARAMETER :: ind_CCO_OOH = 2 
  INTEGER, PARAMETER :: ind_RCO_OOH = 3 
  INTEGER, PARAMETER :: ind_O1D2 = 4 
  INTEGER, PARAMETER :: ind_SO2 = 5 
  INTEGER, PARAMETER :: ind_ALK1 = 6 
  INTEGER, PARAMETER :: ind_HO2H = 7 
  INTEGER, PARAMETER :: ind_PAN = 8 
  INTEGER, PARAMETER :: ind_PAN2 = 9 
  INTEGER, PARAMETER :: ind_PBZN = 10 
  INTEGER, PARAMETER :: ind_MA_PAN = 11 
  INTEGER, PARAMETER :: ind_BACL = 12 
  INTEGER, PARAMETER :: ind_N2O5 = 13 
  INTEGER, PARAMETER :: ind_HONO = 14 
  INTEGER, PARAMETER :: ind_ALK2 = 15 
  INTEGER, PARAMETER :: ind_ALK3 = 16 
  INTEGER, PARAMETER :: ind_TBU_O = 17 
  INTEGER, PARAMETER :: ind_ALK5 = 18 
  INTEGER, PARAMETER :: ind_MEOH = 19 
  INTEGER, PARAMETER :: ind_BZNO2_O = 20 
  INTEGER, PARAMETER :: ind_HNO4 = 21 
  INTEGER, PARAMETER :: ind_COOH = 22 
  INTEGER, PARAMETER :: ind_ARO2 = 23 
  INTEGER, PARAMETER :: ind_ALK4 = 24 
  INTEGER, PARAMETER :: ind_ARO1 = 25 
  INTEGER, PARAMETER :: ind_DCB2 = 26 
  INTEGER, PARAMETER :: ind_DCB3 = 27 
  INTEGER, PARAMETER :: ind_CRES = 28 
  INTEGER, PARAMETER :: ind_DCB1 = 29 
  INTEGER, PARAMETER :: ind_HOCOO = 30 
  INTEGER, PARAMETER :: ind_NPHE = 31 
  INTEGER, PARAMETER :: ind_BALD = 32 
  INTEGER, PARAMETER :: ind_ROOH = 33 
  INTEGER, PARAMETER :: ind_PHEN = 34 
  INTEGER, PARAMETER :: ind_HCOOH = 35 
  INTEGER, PARAMETER :: ind_CO = 36 
  INTEGER, PARAMETER :: ind_MGLY = 37 
  INTEGER, PARAMETER :: ind_ACET = 38 
  INTEGER, PARAMETER :: ind_ETHENE = 39 
  INTEGER, PARAMETER :: ind_HNO3 = 40 
  INTEGER, PARAMETER :: ind_GLY = 41 
  INTEGER, PARAMETER :: ind_BZ_O = 42 
  INTEGER, PARAMETER :: ind_CCO_OH = 43 
  INTEGER, PARAMETER :: ind_R2O2 = 44 
  INTEGER, PARAMETER :: ind_ISOPRENE = 45 
  INTEGER, PARAMETER :: ind_METHACRO = 46 
  INTEGER, PARAMETER :: ind_TRP1 = 47 
  INTEGER, PARAMETER :: ind_RCO_OH = 48 
  INTEGER, PARAMETER :: ind_OLE1 = 49 
  INTEGER, PARAMETER :: ind_ISOPROD = 50 
  INTEGER, PARAMETER :: ind_OLE2 = 51 
  INTEGER, PARAMETER :: ind_MVK = 52 
  INTEGER, PARAMETER :: ind_HCHO = 53 
  INTEGER, PARAMETER :: ind_O3P = 54 
  INTEGER, PARAMETER :: ind_RNO3 = 55 
  INTEGER, PARAMETER :: ind_CCHO = 56 
  INTEGER, PARAMETER :: ind_MEK = 57 
  INTEGER, PARAMETER :: ind_RCHO = 58 
  INTEGER, PARAMETER :: ind_PROD2 = 59 
  INTEGER, PARAMETER :: ind_O3 = 60 
  INTEGER, PARAMETER :: ind_MA_RCO3 = 61 
  INTEGER, PARAMETER :: ind_NO3 = 62 
  INTEGER, PARAMETER :: ind_C_O2 = 63 
  INTEGER, PARAMETER :: ind_RO2_R = 64 
  INTEGER, PARAMETER :: ind_RCO_O2 = 65 
  INTEGER, PARAMETER :: ind_CCO_O2 = 66 
  INTEGER, PARAMETER :: ind_RO2_N = 67 
  INTEGER, PARAMETER :: ind_BZCO_O2 = 68 
  INTEGER, PARAMETER :: ind_HO2 = 69 
  INTEGER, PARAMETER :: ind_NO2 = 70 
  INTEGER, PARAMETER :: ind_NO = 71 
  INTEGER, PARAMETER :: ind_HO = 72 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_M = 73 
  INTEGER, PARAMETER :: ind_O2 = 74 
  INTEGER, PARAMETER :: ind_H2O = 75 
  INTEGER, PARAMETER :: ind_H2 = 76 
  INTEGER, PARAMETER :: ind_CH4 = 77 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(KPPNSP+indf_spc)

  INTEGER, PARAMETER :: indf_M = 1 
  INTEGER, PARAMETER :: indf_O2 = 2 
  INTEGER, PARAMETER :: indf_H2O = 3 
  INTEGER, PARAMETER :: indf_H2 = 4 
  INTEGER, PARAMETER :: indf_CH4 = 5 

END MODULE KPP_Pars

