! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : CMAQ_CB4_Global.f90
! Time                 : Tue Apr 18 15:57:11 2006
! Working directory    : /home/amir/Desktop/KPP/kpp-2.1
! Equation file        : CMAQ_CB4.kpp
! Output root filename : CMAQ_CB4
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE KPP_Glob

  USE KPP_Pars, ONLY: dp, KPPNSP, KPPNRCT, NFIX
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
!  REAL(kind=dp) :: C(KPPNSP)
! VAR - Concentrations of variable species (global)
!  REAL(kind=dp) :: VAR(KPPNVAR)
! FIX - Concentrations of fixed species (global)
  REAL(kind=dp) :: FIX(NFIX)
! VAR, FIX are chunks of array C
!      EQUIVALENCE( C(1),VAR(1) )
!      EQUIVALENCE( C(73),FIX(1) )
! RCONST - Rate constants (global)
  REAL(kind=dp) :: RCONST(KPPNRCT)
! TIME - Current integration time
  REAL(kind=dp) :: TIME
! SUN - Sunlight intensity between [0,1]
!  REAL(kind=dp) :: SUN
! TEMP - Temperature
!  REAL(kind=dp) :: TEMP
! RTOLS - (scalar) Relative tolerance
  REAL(kind=dp) :: RTOLS
! TSTART - Integration start time
  REAL(kind=dp) :: TSTART
! TEND - Integration end time
  REAL(kind=dp) :: TEND
! DT - Integration step
  REAL(kind=dp) :: DT
! ATOL - Absolute tolerance
!  REAL(kind=dp) :: ATOL(KPPNSP)
! RTOL - Relative tolerance
!  REAL(kind=dp) :: RTOL(KPPNSP)
! STEPMIN - Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR
! DDMTYPE - DDM sensitivity w.r.t.: 0=init.val., 1=params
  INTEGER :: DDMTYPE

! INLINED global variable declarations

! INLINED global variable declarations


END MODULE KPP_Glob

